# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:
    inputs:
      caller_repo:
        required: true
        type: string
      caller_branch:
        required: true
        type: string
      caller_ref:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - if: ${{ inputs.caller_repo }} != ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          repository: "Paultergeist/gha_master"

      - if: ${{ inputs.caller_repo }} != ${{ github.repository }}
        run: |
          cd gha_sub1
          git fetch origin ${{ inputs.caller_ref }}
          git checkout ${{ inputs.caller_ref }}

      - name: Print inputs
        run: |
          echo "caller_repo: ${{ inputs.caller_repo }}"
          echo "caller_branch: ${{ inputs.caller_branch }}"
          echo "caller_ref: ${{ inputs.caller_ref }}"

      - name: Show directory contents
        run: |
          pwd
          git remote -v
          git branch -v
          git submodule
          ls -la
          tree
